name: Store-X-Serverless-Lambda

on: 
    push :
        branches: [ main , test ]

permissions:
    id-token: write
    contents: read

jobs: 

 Server-Prodction-Job:
  runs-on: ubuntu-latest
  environment : "PROD"
  env :
      IAM_ROLE: ${{secrets.IAM_ROLE}}
      LAMBDA_FUNCTION_NAME: ${{secrets.LAMBDA_FUNCTION_NAME}}
      REGION: ${{secrets.REGION}}

  steps:


   - name: Configure the aws credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
        role-to-assume: ${{ env.IAM_ROLE }}
        aws-region: ${{ env.REGION}}


   - name: Deploy Lambda Function
     uses: aws-actions/aws-lambda-deploy@v1.1.0
     with:
        function-name: ${{env.LAMBDA_FUNCTION_NAME}}
        code-artifacts-dir: .
        handler: index.handler
        runtime: nodejs22.x
